files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
preserve_hierarchy: true
bundles:
  - 6
project_id_env: ${{ secrets.CROWDIN_PROJECT_ID }}
api_token_env: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
